infraname = "sandbox"
region = "us-east-1"
stage = "prod"
zone = "advipenguins.click"
domain = "tscglobal.advipenguins.click"
subdomain = "tscglobal"
failoverroutingpolicy = "PRIMARY"
setidentifier = "Primary"